# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'self_config_notebook_widget.ui'
##
## Created by: Qt User Interface Compiler version 6.1.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *  # type: ignore
from PySide6.QtGui import *  # type: ignore
from PySide6.QtWidgets import *  # type: ignore
from tkinter_camera import *
from PIL import ImageQt ,Image
from backend_manager import *
import os.path
import logging


class Ui_Config_Widget(object):

    def initialized(self):
        print("class initalized")
        self.batch_path = None
        self.backend_manager = BackendManager()
        self.setupUi(self)
        self.check_session = None
        self.logger=logging.getLogger() 
        self.logger.setLevel(logging.DEBUG)
        file_handler = logging.FileHandler('../Logs/configuration.log')
        print(file_handler)
        formatter    = logging.Formatter('%(asctime)s : %(levelname)s : %(name)s : %(message)s')
        file_handler.setFormatter(formatter)
        self.logger.addHandler(file_handler)
        self.logger.debug('A debug message')

    def setupUi(self, Config_Widget):
        if not Config_Widget.objectName():
            Config_Widget.setObjectName(u"Config_Widget")
        Config_Widget.resize(1792, 1008)
        self.gridLayoutWidget = QWidget(Config_Widget)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(0, 20, 1531, 871))
        self.gridLayout_2 = QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.Notebook_2 = QTabWidget(self.gridLayoutWidget)
        self.Notebook_2.setObjectName(u"Notebook_2")
        self.Notebook_2.setTabShape(QTabWidget.Rounded)
        self.experiment_initialization_3 = QWidget()
        self.experiment_initialization_3.setObjectName(u"experiment_initialization_3")
        self.horizontalLayoutWidget_8 = QWidget(self.experiment_initialization_3)
        self.horizontalLayoutWidget_8.setObjectName(u"horizontalLayoutWidget_8")
        self.horizontalLayoutWidget_8.setGeometry(QRect(10, 80, 1441, 351))
        self.horizontalLayout_13 = QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_13.setObjectName(u"horizontalLayout_13")
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_28 = QGridLayout()
        self.gridLayout_28.setObjectName(u"gridLayout_28")
        self.groupBox_22 = QGroupBox(self.horizontalLayoutWidget_8)
        self.groupBox_22.setObjectName(u"groupBox_22")
        self.So_com1 = QComboBox(self.groupBox_22)
        self.So_com1.setObjectName(u"So_com1")
        self.So_com1.setGeometry(QRect(100, 20, 281, 41))
        self.label_199 = QLabel(self.groupBox_22)
        self.label_199.setObjectName(u"label_199")
        self.label_199.setGeometry(QRect(110, 60, 71, 16))
        self.So_com2 = QComboBox(self.groupBox_22)
        self.So_com2.setObjectName(u"So_com2")
        self.So_com2.setGeometry(QRect(100, 90, 281, 41))
        self.label_200 = QLabel(self.groupBox_22)
        self.label_200.setObjectName(u"label_200")
        self.label_200.setGeometry(QRect(110, 130, 71, 16))
        self.S1 = QLineEdit(self.groupBox_22)
        self.S1.setObjectName(u"S1")
        self.S1.setGeometry(QRect(110, 160, 131, 41))
        self.S2 = QLineEdit(self.groupBox_22)
        self.S2.setObjectName(u"S2")
        self.S2.setGeometry(QRect(250, 160, 131, 41))
        self.label_201 = QLabel(self.groupBox_22)
        self.label_201.setObjectName(u"label_201")
        self.label_201.setGeometry(QRect(110, 200, 71, 16))
        self.label_202 = QLabel(self.groupBox_22)
        self.label_202.setObjectName(u"label_202")
        self.label_202.setGeometry(QRect(250, 200, 71, 16))
        self.S3 = QLineEdit(self.groupBox_22)
        self.S3.setObjectName(u"S3")
        self.S3.setGeometry(QRect(110, 230, 61, 41))
        self.S4 = QLineEdit(self.groupBox_22)
        self.S4.setObjectName(u"S4")
        self.S4.setGeometry(QRect(180, 230, 61, 41))
        self.S5 = QLineEdit(self.groupBox_22)
        self.S5.setObjectName(u"S5")
        self.S5.setGeometry(QRect(250, 230, 61, 41))
        self.S6 = QLineEdit(self.groupBox_22)
        self.S6.setObjectName(u"S6")
        self.S6.setGeometry(QRect(320, 230, 61, 41))
        self.label_203 = QLabel(self.groupBox_22)
        self.label_203.setObjectName(u"label_203")
        self.label_203.setGeometry(QRect(110, 270, 71, 16))
        self.label_204 = QLabel(self.groupBox_22)
        self.label_204.setObjectName(u"label_204")
        self.label_204.setGeometry(QRect(180, 270, 71, 16))
        self.label_205 = QLabel(self.groupBox_22)
        self.label_205.setObjectName(u"label_205")
        self.label_205.setGeometry(QRect(250, 270, 71, 16))
        self.label_206 = QLabel(self.groupBox_22)
        self.label_206.setObjectName(u"label_206")
        self.label_206.setGeometry(QRect(320, 270, 71, 16))

        self.gridLayout_28.addWidget(self.groupBox_22, 0, 0, 1, 1)


        self.horizontalLayout_13.addLayout(self.gridLayout_28)

        self.gridLayout_29 = QGridLayout()
        self.gridLayout_29.setObjectName(u"gridLayout_29")
        self.groupBox_30 = QGroupBox(self.horizontalLayoutWidget_8)
        self.groupBox_30.setObjectName(u"groupBox_30")
        self.Ce_com1 = QComboBox(self.groupBox_30)
        self.Ce_com1.setObjectName(u"Ce_com1")
        self.Ce_com1.setGeometry(QRect(110, 20, 281, 41))
        self.Ce_com2 = QComboBox(self.groupBox_30)
        self.Ce_com2.setObjectName(u"Ce_com2")
        self.Ce_com2.setGeometry(QRect(110, 90, 281, 41))
        self.Ce1 = QLineEdit(self.groupBox_30)
        self.Ce1.setObjectName(u"Ce1")
        self.Ce1.setGeometry(QRect(120, 160, 131, 41))
        self.label_207 = QLabel(self.groupBox_30)
        self.label_207.setObjectName(u"label_207")
        self.label_207.setGeometry(QRect(120, 60, 71, 16))
        self.label_208 = QLabel(self.groupBox_30)
        self.label_208.setObjectName(u"label_208")
        self.label_208.setGeometry(QRect(120, 130, 71, 16))
        self.label_209 = QLabel(self.groupBox_30)
        self.label_209.setObjectName(u"label_209")
        self.label_209.setGeometry(QRect(120, 200, 71, 16))

        self.gridLayout_29.addWidget(self.groupBox_30, 0, 0, 1, 1)


        self.horizontalLayout_13.addLayout(self.gridLayout_29)

        self.gridLayout_30 = QGridLayout()
        self.gridLayout_30.setObjectName(u"gridLayout_30")
        self.groupBox_31 = QGroupBox(self.horizontalLayoutWidget_8)
        self.groupBox_31.setObjectName(u"groupBox_31")
        self.C1 = QLineEdit(self.groupBox_31)
        self.C1.setObjectName(u"C1")
        self.C1.setGeometry(QRect(90, 20, 81, 41))
        self.C2 = QLineEdit(self.groupBox_31)
        self.C2.setObjectName(u"C2")
        self.C2.setGeometry(QRect(200, 20, 81, 41))
        self.Co_com1 = QComboBox(self.groupBox_31)
        self.Co_com1.setObjectName(u"Co_com1")
        self.Co_com1.setGeometry(QRect(300, 20, 91, 41))
        self.C3 = QLineEdit(self.groupBox_31)
        self.C3.setObjectName(u"C3")
        self.C3.setGeometry(QRect(90, 90, 81, 41))
        self.C4 = QLineEdit(self.groupBox_31)
        self.C4.setObjectName(u"C4")
        self.C4.setGeometry(QRect(200, 90, 81, 41))
        self.C5 = QLineEdit(self.groupBox_31)
        self.C5.setObjectName(u"C5")
        self.C5.setGeometry(QRect(90, 160, 81, 41))
        self.C6 = QLineEdit(self.groupBox_31)
        self.C6.setObjectName(u"C6")
        self.C6.setGeometry(QRect(200, 160, 81, 41))
        self.C8 = QLineEdit(self.groupBox_31)
        self.C8.setObjectName(u"C8")
        self.C8.setGeometry(QRect(90, 230, 131, 41))
        self.C9 = QLineEdit(self.groupBox_31)
        self.C9.setObjectName(u"C9")
        self.C9.setGeometry(QRect(270, 230, 131, 41))
        self.label_210 = QLabel(self.groupBox_31)
        self.label_210.setObjectName(u"label_210")
        self.label_210.setGeometry(QRect(90, 60, 81, 16))
        self.label_211 = QLabel(self.groupBox_31)
        self.label_211.setObjectName(u"label_211")
        self.label_211.setGeometry(QRect(200, 60, 71, 16))
        self.label_212 = QLabel(self.groupBox_31)
        self.label_212.setObjectName(u"label_212")
        self.label_212.setGeometry(QRect(310, 60, 71, 16))
        self.label_213 = QLabel(self.groupBox_31)
        self.label_213.setObjectName(u"label_213")
        self.label_213.setGeometry(QRect(90, 130, 71, 16))
        self.label_214 = QLabel(self.groupBox_31)
        self.label_214.setObjectName(u"label_214")
        self.label_214.setGeometry(QRect(200, 130, 71, 16))
        self.label_215 = QLabel(self.groupBox_31)
        self.label_215.setObjectName(u"label_215")
        self.label_215.setGeometry(QRect(90, 200, 71, 16))
        self.label_216 = QLabel(self.groupBox_31)
        self.label_216.setObjectName(u"label_216")
        self.label_216.setGeometry(QRect(200, 200, 71, 16))
        self.label_217 = QLabel(self.groupBox_31)
        self.label_217.setObjectName(u"label_217")
        self.label_217.setGeometry(QRect(90, 270, 71, 16))
        self.label_218 = QLabel(self.groupBox_31)
        self.label_218.setObjectName(u"label_218")
        self.label_218.setGeometry(QRect(270, 270, 111, 16))
        self.C6_2 = QLineEdit(self.groupBox_31)
        self.C6_2.setObjectName(u"C6_2")
        self.C6_2.setGeometry(QRect(310, 160, 81, 41))
        self.label_219 = QLabel(self.groupBox_31)
        self.label_219.setObjectName(u"label_219")
        self.label_219.setGeometry(QRect(310, 200, 71, 16))

        self.gridLayout_30.addWidget(self.groupBox_31, 0, 0, 1, 1)


        self.horizontalLayout_13.addLayout(self.gridLayout_30)

        self.horizontalLayoutWidget_9 = QWidget(self.experiment_initialization_3)
        self.horizontalLayoutWidget_9.setObjectName(u"horizontalLayoutWidget_9")
        self.horizontalLayoutWidget_9.setGeometry(QRect(10, 440, 1441, 381))
        self.horizontalLayout_14 = QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_14.setObjectName(u"horizontalLayout_14")
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_31 = QGridLayout()
        self.gridLayout_31.setObjectName(u"gridLayout_31")
        self.groupBox_32 = QGroupBox(self.horizontalLayoutWidget_9)
        self.groupBox_32.setObjectName(u"groupBox_32")
        self.St_com1 = QComboBox(self.groupBox_32)
        self.St_com1.setObjectName(u"St_com1")
        self.St_com1.setGeometry(QRect(100, 30, 281, 41))
        self.St_com2 = QComboBox(self.groupBox_32)
        self.St_com2.setObjectName(u"St_com2")
        self.St_com2.setGeometry(QRect(100, 110, 281, 41))
        self.St_com3 = QComboBox(self.groupBox_32)
        self.St_com3.setObjectName(u"St_com3")
        self.St_com3.setGeometry(QRect(100, 190, 281, 41))
        self.label_220 = QLabel(self.groupBox_32)
        self.label_220.setObjectName(u"label_220")
        self.label_220.setGeometry(QRect(110, 70, 101, 16))
        self.label_221 = QLabel(self.groupBox_32)
        self.label_221.setObjectName(u"label_221")
        self.label_221.setGeometry(QRect(110, 150, 101, 16))
        self.label_222 = QLabel(self.groupBox_32)
        self.label_222.setObjectName(u"label_222")
        self.label_222.setGeometry(QRect(110, 230, 101, 16))

        self.gridLayout_31.addWidget(self.groupBox_32, 0, 0, 1, 1)


        self.horizontalLayout_14.addLayout(self.gridLayout_31)

        self.gridLayout_32 = QGridLayout()
        self.gridLayout_32.setObjectName(u"gridLayout_32")
        self.groupBox_33 = QGroupBox(self.horizontalLayoutWidget_9)
        self.groupBox_33.setObjectName(u"groupBox_33")
        self.E_com1 = QComboBox(self.groupBox_33)
        self.E_com1.setObjectName(u"E_com1")
        self.E_com1.setGeometry(QRect(120, 30, 281, 41))
        self.E_com2 = QComboBox(self.groupBox_33)
        self.E_com2.setObjectName(u"E_com2")
        self.E_com2.setGeometry(QRect(120, 110, 281, 41))
        self.E1 = QLineEdit(self.groupBox_33)
        self.E1.setObjectName(u"E1")
        self.E1.setGeometry(QRect(130, 190, 131, 41))
        self.E2 = QLineEdit(self.groupBox_33)
        self.E2.setObjectName(u"E2")
        self.E2.setGeometry(QRect(282, 190, 121, 41))
        self.label_223 = QLabel(self.groupBox_33)
        self.label_223.setObjectName(u"label_223")
        self.label_223.setGeometry(QRect(130, 70, 111, 16))
        self.label_224 = QLabel(self.groupBox_33)
        self.label_224.setObjectName(u"label_224")
        self.label_224.setGeometry(QRect(130, 150, 121, 16))
        self.label_225 = QLabel(self.groupBox_33)
        self.label_225.setObjectName(u"label_225")
        self.label_225.setGeometry(QRect(130, 230, 101, 16))
        self.label_226 = QLabel(self.groupBox_33)
        self.label_226.setObjectName(u"label_226")
        self.label_226.setGeometry(QRect(280, 230, 101, 16))

        self.gridLayout_32.addWidget(self.groupBox_33, 0, 0, 1, 1)


        self.horizontalLayout_14.addLayout(self.gridLayout_32)

        self.gridLayout_33 = QGridLayout()
        self.gridLayout_33.setObjectName(u"gridLayout_33")
        self.groupBox_34 = QGroupBox(self.horizontalLayoutWidget_9)
        self.groupBox_34.setObjectName(u"groupBox_34")
        self.A_com1 = QComboBox(self.groupBox_34)
        self.A_com1.setObjectName(u"A_com1")
        self.A_com1.setGeometry(QRect(90, 30, 141, 41))
        self.A_com2 = QComboBox(self.groupBox_34)
        self.A_com2.setObjectName(u"A_com2")
        self.A_com2.setGeometry(QRect(270, 30, 141, 41))
        self.A1 = QLineEdit(self.groupBox_34)
        self.A1.setObjectName(u"A1")
        self.A1.setGeometry(QRect(100, 110, 131, 41))
        self.A_com3 = QComboBox(self.groupBox_34)
        self.A_com3.setObjectName(u"A_com3")
        self.A_com3.setGeometry(QRect(270, 110, 141, 41))
        self.A2 = QLineEdit(self.groupBox_34)
        self.A2.setObjectName(u"A2")
        self.A2.setGeometry(QRect(100, 190, 311, 41))
        self.label_227 = QLabel(self.groupBox_34)
        self.label_227.setObjectName(u"label_227")
        self.label_227.setGeometry(QRect(100, 70, 81, 16))
        self.label_228 = QLabel(self.groupBox_34)
        self.label_228.setObjectName(u"label_228")
        self.label_228.setGeometry(QRect(280, 70, 91, 16))
        self.label_229 = QLabel(self.groupBox_34)
        self.label_229.setObjectName(u"label_229")
        self.label_229.setGeometry(QRect(100, 150, 81, 16))
        self.label_230 = QLabel(self.groupBox_34)
        self.label_230.setObjectName(u"label_230")
        self.label_230.setGeometry(QRect(280, 150, 71, 16))
        self.label_231 = QLabel(self.groupBox_34)
        self.label_231.setObjectName(u"label_231")
        self.label_231.setGeometry(QRect(100, 230, 141, 16))
        self.horizontalLayoutWidget_10 = QWidget(self.groupBox_34)
        self.horizontalLayoutWidget_10.setObjectName(u"horizontalLayoutWidget_10")
        self.horizontalLayoutWidget_10.setGeometry(QRect(10, 320, 451, 51))
        self.horizontalLayout_6 = QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.button_submit_database = QPushButton(self.horizontalLayoutWidget_10)
        self.button_submit_database.setObjectName(u"button_submit_database")

        self.horizontalLayout_6.addWidget(self.button_submit_database)

        self.button_edit_experiment = QPushButton(self.horizontalLayoutWidget_10)
        self.button_edit_experiment.setObjectName(u"button_edit_experiment")

        self.horizontalLayout_6.addWidget(self.button_edit_experiment)


        self.gridLayout_33.addWidget(self.groupBox_34, 0, 0, 1, 1)


        self.horizontalLayout_14.addLayout(self.gridLayout_33)

        self.horizontalLayoutWidget_11 = QWidget(self.experiment_initialization_3)
        self.horizontalLayoutWidget_11.setObjectName(u"horizontalLayoutWidget_11")
        self.horizontalLayoutWidget_11.setGeometry(QRect(660, 10, 191, 51))
        self.horizontalLayout_15 = QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_15.setObjectName(u"horizontalLayout_15")
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.Load_meta_data_experiment_12 = QPushButton(self.horizontalLayoutWidget_11)
        self.Load_meta_data_experiment_12.setObjectName(u"Load_meta_data_experiment_12")

        self.horizontalLayout_15.addWidget(self.Load_meta_data_experiment_12)

        self.Notebook_2.addTab(self.experiment_initialization_3, "")
        self.batch_communication_3 = QWidget()
        self.batch_communication_3.setObjectName(u"batch_communication_3")
        self.groupBox_17 = QGroupBox(self.batch_communication_3)
        self.groupBox_17.setObjectName(u"groupBox_17")
        self.groupBox_17.setGeometry(QRect(20, 30, 541, 181))
        self.Batch1 = QLineEdit(self.groupBox_17)
        self.Batch1.setObjectName(u"Batch1")
        self.Batch1.setGeometry(QRect(40, 30, 451, 41))
        self.button_batch_1 = QPushButton(self.groupBox_17)
        self.button_batch_1.setObjectName(u"button_batch_1")
        self.button_batch_1.setGeometry(QRect(10, 110, 161, 31))
        self.button_control_1 = QPushButton(self.groupBox_17)
        self.button_control_1.setObjectName(u"button_control_1")
        self.button_control_1.setGeometry(QRect(360, 110, 171, 31))
        self.label_4 = QLabel(self.groupBox_17)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(40, 70, 111, 16))
        self.button_control_2 = QPushButton(self.groupBox_17)
        self.button_control_2.setObjectName(u"button_control_2")
        self.button_control_2.setGeometry(QRect(180, 110, 171, 31))
        self.groupBox_18 = QGroupBox(self.batch_communication_3)
        self.groupBox_18.setObjectName(u"groupBox_18")
        self.groupBox_18.setGeometry(QRect(580, 30, 851, 781))
        self.scrollArea_3 = QScrollArea(self.groupBox_18)
        self.scrollArea_3.setObjectName(u"scrollArea_3")
        self.scrollArea_3.setGeometry(QRect(40, 60, 361, 541))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollAreaWidgetContents_3 = QWidget()
        self.scrollAreaWidgetContents_3.setObjectName(u"scrollAreaWidgetContents_3")
        self.scrollAreaWidgetContents_3.setGeometry(QRect(0, 0, 359, 539))
        self.sub_command1 = QTextEdit(self.scrollAreaWidgetContents_3)
        self.sub_command1.setObjectName(u"sub_command1")
        self.sub_command1.setGeometry(QRect(0, 0, 361, 541))
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.label_40 = QLabel(self.groupBox_18)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(40, 40, 181, 20))
        self.label_41 = QLabel(self.groupBox_18)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(440, 40, 171, 20))
        self.receive_command1 = QTextEdit(self.groupBox_18)
        self.receive_command1.setObjectName(u"receive_command1")
        self.receive_command1.setGeometry(QRect(440, 60, 391, 241))
        self.response_command_1 = QTextEdit(self.groupBox_18)
        self.response_command_1.setObjectName(u"response_command_1")
        self.response_command_1.setGeometry(QRect(440, 370, 391, 231))
        self.label_42 = QLabel(self.groupBox_18)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(440, 350, 231, 20))
        self.button_submit_command = QPushButton(self.groupBox_18)
        self.button_submit_command.setObjectName(u"button_submit_command")
        self.button_submit_command.setGeometry(QRect(60, 640, 171, 31))
        self.button_clear_window = QPushButton(self.groupBox_18)
        self.button_clear_window.setObjectName(u"button_clear_window")
        self.button_clear_window.setGeometry(QRect(250, 640, 151, 31))
        self.groupBox_19 = QGroupBox(self.batch_communication_3)
        self.groupBox_19.setObjectName(u"groupBox_19")
        self.groupBox_19.setGeometry(QRect(20, 230, 541, 181))
        self.Template_path1 = QLineEdit(self.groupBox_19)
        self.Template_path1.setObjectName(u"Template_path1")
        self.Template_path1.setGeometry(QRect(40, 40, 451, 41))
        self.button_open_template_wizard = QPushButton(self.groupBox_19)
        self.button_open_template_wizard.setObjectName(u"button_open_template_wizard")
        self.button_open_template_wizard.setGeometry(QRect(50, 110, 181, 31))
        self.button_use_template_wizard = QPushButton(self.groupBox_19)
        self.button_use_template_wizard.setObjectName(u"button_use_template_wizard")
        self.button_use_template_wizard.setGeometry(QRect(290, 110, 191, 31))
        self.label_5 = QLabel(self.groupBox_19)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(40, 80, 151, 16))
        self.Notebook_2.addTab(self.batch_communication_3, "")
        self.camera_3 = QWidget()
        self.camera_3.setObjectName(u"camera_3")
        self.pushButton = QPushButton(self.camera_3)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(650, 20, 191, 41))
        self.groupBox = QGroupBox(self.camera_3)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(80, 110, 641, 571))
        self.Camera_Live_Feed = QGraphicsView(self.groupBox)
        self.Camera_Live_Feed.setObjectName(u"Camera_Live_Feed")
        self.Camera_Live_Feed.setGeometry(QRect(40, 40, 561, 451))
        self.button_start_camera = QPushButton(self.groupBox)
        self.button_start_camera.setObjectName(u"button_start_camera")
        self.button_start_camera.setGeometry(QRect(40, 510, 182, 23))
        self.button_stop_camera = QPushButton(self.groupBox)
        self.button_stop_camera.setObjectName(u"button_stop_camera")
        self.button_stop_camera.setGeometry(QRect(228, 510, 183, 23))
        self.button_take_snapshot = QPushButton(self.groupBox)
        self.button_take_snapshot.setObjectName(u"button_take_snapshot")
        self.button_take_snapshot.setGeometry(QRect(417, 510, 182, 23))
        self.groupBox_2 = QGroupBox(self.camera_3)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(780, 110, 641, 571))
        self.Taken_Snapshot = QGraphicsView(self.groupBox_2)
        self.Taken_Snapshot.setObjectName(u"Taken_Snapshot")
        self.Taken_Snapshot.setGeometry(QRect(40, 40, 561, 451))
        self.button_transfer_to_labbook = QPushButton(self.groupBox_2)
        self.button_transfer_to_labbook.setObjectName(u"button_transfer_to_labbook")
        self.button_transfer_to_labbook.setGeometry(QRect(420, 510, 182, 23))
        self.button_discard_snapshot = QPushButton(self.groupBox_2)
        self.button_discard_snapshot.setObjectName(u"button_discard_snapshot")
        self.button_discard_snapshot.setGeometry(QRect(43, 510, 182, 23))
        self.button_save_snapshot = QPushButton(self.groupBox_2)
        self.button_save_snapshot.setObjectName(u"button_save_snapshot")
        self.button_save_snapshot.setGeometry(QRect(231, 510, 183, 23))
        self.Notebook_2.addTab(self.camera_3, "")

        self.gridLayout_2.addWidget(self.Notebook_2, 0, 0, 1, 1)


        self.retranslateUi(Config_Widget)

        self.Notebook_2.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(Config_Widget)
    # setupUi

    def retranslateUi(self, Config_Widget):
        Config_Widget.setWindowTitle(QCoreApplication.translate("Config_Widget", u"Form", None))
        self.groupBox_22.setTitle(QCoreApplication.translate("Config_Widget", u"Solutions", None))
        self.label_199.setText(QCoreApplication.translate("Config_Widget", u"EC Type", None))
        self.label_200.setText(QCoreApplication.translate("Config_Widget", u"IC  Type", None))
        self.S1.setText("")
        self.label_201.setText(QCoreApplication.translate("Config_Widget", u"EC Lot #", None))
        self.label_202.setText(QCoreApplication.translate("Config_Widget", u"IC lot #", None))
        self.label_203.setText(QCoreApplication.translate("Config_Widget", u"T [\u00b0C]", None))
        self.label_204.setText(QCoreApplication.translate("Config_Widget", u"F [ml/min]", None))
        self.label_205.setText(QCoreApplication.translate("Config_Widget", u"I [nm]", None))
        self.label_206.setText(QCoreApplication.translate("Config_Widget", u"e", None))
        self.groupBox_30.setTitle(QCoreApplication.translate("Config_Widget", u"Cells", None))
        self.label_207.setText(QCoreApplication.translate("Config_Widget", u"License ID", None))
        self.label_208.setText(QCoreApplication.translate("Config_Widget", u"Cell line", None))
        self.label_209.setText(QCoreApplication.translate("Config_Widget", u"Passage #", None))
        self.groupBox_31.setTitle(QCoreApplication.translate("Config_Widget", u"Compound", None))
        self.label_210.setText(QCoreApplication.translate("Config_Widget", u"Sample Code", None))
        self.label_211.setText(QCoreApplication.translate("Config_Widget", u"Lot #", None))
        self.label_212.setText(QCoreApplication.translate("Config_Widget", u"Salt Code", None))
        self.label_213.setText(QCoreApplication.translate("Config_Widget", u"Sample Id", None))
        self.label_214.setText(QCoreApplication.translate("Config_Widget", u"MW [Da]", None))
        self.label_215.setText(QCoreApplication.translate("Config_Widget", u"Weight [mg]", None))
        self.label_216.setText(QCoreApplication.translate("Config_Widget", u"Solvent", None))
        self.label_217.setText(QCoreApplication.translate("Config_Widget", u"Stocks [mM]", None))
        self.label_218.setText(QCoreApplication.translate("Config_Widget", u"Concentration [\u00b5M]", None))
        self.label_219.setText(QCoreApplication.translate("Config_Widget", u"Volumn [\u00b5L]", None))
        self.groupBox_32.setTitle(QCoreApplication.translate("Config_Widget", u"Staff", None))
        self.label_220.setText(QCoreApplication.translate("Config_Widget", u"Study director", None))
        self.label_221.setText(QCoreApplication.translate("Config_Widget", u"Technician", None))
        self.label_222.setText(QCoreApplication.translate("Config_Widget", u"Laboratory Code", None))
        self.groupBox_33.setTitle(QCoreApplication.translate("Config_Widget", u"Experiment Protocol", None))
        self.label_223.setText(QCoreApplication.translate("Config_Widget", u"Protocol Files", None))
        self.label_224.setText(QCoreApplication.translate("Config_Widget", u"Pulse description", None))
        self.label_225.setText(QCoreApplication.translate("Config_Widget", u"N", None))
        self.label_226.setText(QCoreApplication.translate("Config_Widget", u"Done", None))
        self.groupBox_34.setTitle(QCoreApplication.translate("Config_Widget", u"Archiving", None))
        self.label_227.setText(QCoreApplication.translate("Config_Widget", u"Model Code", None))
        self.label_228.setText(QCoreApplication.translate("Config_Widget", u"Project Code", None))
        self.label_229.setText(QCoreApplication.translate("Config_Widget", u"Study Code", None))
        self.label_230.setText(QCoreApplication.translate("Config_Widget", u"Data path", None))
        self.label_231.setText(QCoreApplication.translate("Config_Widget", u"File name template", None))
        self.button_submit_database.setText(QCoreApplication.translate("Config_Widget", u"Submit Data to Database", None))
        self.button_edit_experiment.setText(QCoreApplication.translate("Config_Widget", u"Edit Data", None))
        self.Load_meta_data_experiment_12.setText(QCoreApplication.translate("Config_Widget", u"Load Metadata", None))
        self.Notebook_2.setTabText(self.Notebook_2.indexOf(self.experiment_initialization_3), QCoreApplication.translate("Config_Widget", u"Experiment Initialization", None))
        self.groupBox_17.setTitle(QCoreApplication.translate("Config_Widget", u"Set Batch Communication Settings", None))
        self.button_batch_1.setText(QCoreApplication.translate("Config_Widget", u"Set Batch Path", None))
        self.button_control_1.setText(QCoreApplication.translate("Config_Widget", u"Generate Control File", None))
        self.label_4.setText(QCoreApplication.translate("Config_Widget", u"Control File Path", None))
        self.button_control_2.setText(QCoreApplication.translate("Config_Widget", u"Check Control File", None))
        self.groupBox_18.setTitle(QCoreApplication.translate("Config_Widget", u"Batch Communication Control", None))
        self.label_40.setText(QCoreApplication.translate("Config_Widget", u"Submit your Commands", None))
        self.label_41.setText(QCoreApplication.translate("Config_Widget", u"Control File received", None))
        self.label_42.setText(QCoreApplication.translate("Config_Widget", u"Batch Communication Response", None))
        self.button_submit_command.setText(QCoreApplication.translate("Config_Widget", u"Submit", None))
        self.button_clear_window.setText(QCoreApplication.translate("Config_Widget", u"Clear Window", None))
        self.groupBox_19.setTitle(QCoreApplication.translate("Config_Widget", u"Template Wizard", None))
        self.button_open_template_wizard.setText(QCoreApplication.translate("Config_Widget", u"Open Template Wizard", None))
        self.button_use_template_wizard.setText(QCoreApplication.translate("Config_Widget", u"Use Template", None))
        self.label_5.setText(QCoreApplication.translate("Config_Widget", u"Wizard Template Path", None))
        self.Notebook_2.setTabText(self.Notebook_2.indexOf(self.batch_communication_3), QCoreApplication.translate("Config_Widget", u"Batch Communication", None))
        self.pushButton.setText(QCoreApplication.translate("Config_Widget", u"Initalize Camera", None))
        self.groupBox.setTitle(QCoreApplication.translate("Config_Widget", u"Live Camera Feed", None))
        self.button_start_camera.setText(QCoreApplication.translate("Config_Widget", u"Start Camera", None))
        self.button_stop_camera.setText(QCoreApplication.translate("Config_Widget", u"Stop Camera", None))
        self.button_take_snapshot.setText(QCoreApplication.translate("Config_Widget", u"Take Snapshot", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Config_Widget", u"Snapshot Overview", None))
        self.button_transfer_to_labbook.setText(QCoreApplication.translate("Config_Widget", u"Transfer to Labbook", None))
        self.button_discard_snapshot.setText(QCoreApplication.translate("Config_Widget", u"Discard Snapshot", None))
        self.button_save_snapshot.setText(QCoreApplication.translate("Config_Widget", u"Save Snapshot", None))
        self.Notebook_2.setTabText(self.Notebook_2.indexOf(self.camera_3), QCoreApplication.translate("Config_Widget", u"Camera", None))
    # retranslateUi

    def meta_open_directory(self):
        '''opens a filedialog where a user can select a desired directory. Once the directory has been choosen,
        it's data will be loaded immediately into the databse'''
        # open the directory
        dir_path = QFileDialog.getOpenFileUrl()
        # save the path in the manager class
        self.configuration_metadata._directory_path = dir_path

    def open_batch_path(self):
        """ choose the path were the batch communication file should
        be located
        --> checks for the exisitence of the file
        --> check control file button should indicate if file is already 
        there
         """
        batch_path = self.backend_manager.set_batch_path()
        if batch_path:
            self.Batch1.setText(batch_path)
            self.batch_path = batch_path
            file_existence = self.backend_manager.check_input_file_existence()
            if file_existence is True:
                print("yeah")
                self.button_control_2.setStyleSheet("background-color: green")
                self.button_control_1.setEnabled(False)
            else:
                self.button_control_2.setStyleSheet("background-color: red")
                self.button_control_1.setEnabled(True)

        else:
            self.Batch1.setText("please select a Path for the Patch File")


    def generate_control_file(self):
        """ if control file is non-existent generate a file """
        self.backend_manager.create_ascii_file_from_template()

    def initialize_camera(self):
        """ Basler camera initalizing  
        ToDO: """
        print("stuff worked")
        self.camera = BayerCamera()
        #initialize the camera 
        camera_status = self.camera.init_camera()
        self.scence_trial = QGraphicsScene(self)
        if camera_status is None:
            self.scence_trial.addText("is not working")
            self.Camera_Live_Feed.setScene(self.scence_trial)
            self.button_start_camera.setEnabled(False)
            self.button_stop_camera.setEnabled(False)
            self.button_take_snapshot.setEnabled(False)

        else:
            print("Camera is connected")
            self.scence_trial.addText("Please start the Camera via the Start Camera Button")
            self.Camera_Live_Feed.setScene(self.scence_trial)

    def start_camera_timer(self):
        """ added the asnychronous Qtimer for the Camera initalizion"""
        self.start_cam = QTimer()
        self.start_cam.timeout.connect(self.start_camera)   
        self.start_cam.start(222)  # (333,self.start_camera)

    def start_camera(self):
        """ grab the current picture one by one with 50 FPS """
        camera_image = self.camera.grab_video()
        imgs = Image.fromarray(camera_image)
        image = imgs.resize((561,451), Image.ANTIALIAS)
        imgqt = ImageQt.ImageQt(image)
        self.trial_figure = QPixmap.fromImage(imgqt)
        self.scence_trial.clear()
        self.scence_trial.addPixmap(self.trial_figure)
        print(camera_image)

    def stop_camera(self):
        """ stop the camera timer """
        print("yeah I m here for the camera")
        self.start_cam.stop()

    def show_snapshot(self):
        """ does transfer the current snapshot to the galery view """
        self.snapshot_scence = QGraphicsScene(self)
        self.Taken_Snapshot.setScene(self.snapshot_scence)
        self.snapshot_scence.addPixmap(self.trial_figure)

    def get_commands_from_textinput(self):
        print("get commands")
        self.res = self.sub_command1.toPlainText()
        self.logger.debug(f'Batch communication input: {self.res}')
        self.sub_command1.clear()
        
        print(self.res)
        self.backend_manager.send_text_input(self.res)
        if self.check_session:
            print("still checking commands")
        else:
            self.check_session = QTimer()
            self.check_session.timeout.connect(self.update_page)
            self.check_session.start(1000)
        #return self.res

    def update_page(self):
        """ asynchronouse updating of the file """
        response_file = self.backend_manager.update_response_file_content()
        input_file = self.backend_manager.update_control_file_content()
        self.receive_command1.clear()
        self.response_command_1.clear()
        self.receive_command1.insertPlainText(input_file)
        self.response_command_1.insertPlainText(response_file)


    def end_communication_control(self):
        """ stop the batch communication and clear all fields """
        print("communication end")
        if self.check_session:
            self.check_session.stop()
            self.check_session = None
            self.receive_command1.clear()
            self.response_command_1.clear()
            self.sub_command1.clear()

class Config_Widget(QWidget,Ui_Config_Widget):
    def __init__(self,parent = None):
        QWidget.__init__(self,parent)
        self.initialized()