# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'self_config_notebook_widget.ui'
##
## Created by: Qt User Interface Compiler version 6.1.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *  # type: ignore
from PySide6.QtGui import *  # type: ignore
from PySide6.QtWidgets import *  # type: ignore
from PIL import ImageQt ,Image
from backend_manager import *
import os.path
import logging
from dragable_label import *
from tkinter_camera import *
from time import sleep
import pandas as pd
from dropable_list_view import ListView
from plotting_pyqt import PlotClass
import pyqtgraph as pg
from pyqtgraph import PlotWidget, plot
pg.setConfigOption('foreground', '#ff8117')
from dvg_pyqtgraph_threadsafe import PlotCurve

class Ui_Config_Widget(object):

    

    def setupUi(self, Config_Widget):
        if not Config_Widget.objectName():
            Config_Widget.setObjectName(u"Config_Widget")
        Config_Widget.resize(1634, 1047)
        self.gridLayoutWidget = QWidget(Config_Widget)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(0, 20, 1601, 991))
        self.gridLayout_2 = QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.Notebook_2 = QTabWidget(self.gridLayoutWidget)
        self.Notebook_2.setObjectName(u"Notebook_2")
        self.Notebook_2.setTabShape(QTabWidget.Rounded)
        self.experiment_initialization_3 = QWidget()
        self.experiment_initialization_3.setObjectName(u"experiment_initialization_3")
        self.meta_data_loading_1 = QStackedWidget(self.experiment_initialization_3)
        self.meta_data_loading_1.setObjectName(u"meta_data_loading_1")
        self.meta_data_loading_1.setGeometry(QRect(-10, 60, 1601, 901))
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.horizontalLayoutWidget_9 = QWidget(self.page)
        self.horizontalLayoutWidget_9.setObjectName(u"horizontalLayoutWidget_9")
        self.horizontalLayoutWidget_9.setGeometry(QRect(40, 410, 1551, 461))
        self.horizontalLayout_14 = QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_14.setObjectName(u"horizontalLayout_14")
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_31 = QGridLayout()
        self.gridLayout_31.setObjectName(u"gridLayout_31")
        self.groupBox_32 = QGroupBox(self.horizontalLayoutWidget_9)
        self.groupBox_32.setObjectName(u"groupBox_32")
        self.St_com1 = QComboBox(self.groupBox_32)
        self.St_com1.setObjectName(u"St_com1")
        self.St_com1.setGeometry(QRect(100, 100, 281, 41))
        self.St_com2 = QComboBox(self.groupBox_32)
        self.St_com2.setObjectName(u"St_com2")
        self.St_com2.setGeometry(QRect(100, 180, 281, 41))
        self.St_com3 = QComboBox(self.groupBox_32)
        self.St_com3.setObjectName(u"St_com3")
        self.St_com3.setGeometry(QRect(100, 260, 281, 41))
        self.label_220 = QLabel(self.groupBox_32)
        self.label_220.setObjectName(u"label_220")
        self.label_220.setGeometry(QRect(100, 140, 101, 16))
        self.label_221 = QLabel(self.groupBox_32)
        self.label_221.setObjectName(u"label_221")
        self.label_221.setGeometry(QRect(100, 220, 101, 16))
        self.label_222 = QLabel(self.groupBox_32)
        self.label_222.setObjectName(u"label_222")
        self.label_222.setGeometry(QRect(100, 300, 101, 16))

        self.gridLayout_31.addWidget(self.groupBox_32, 0, 0, 1, 1)


        self.horizontalLayout_14.addLayout(self.gridLayout_31)

        self.gridLayout_32 = QGridLayout()
        self.gridLayout_32.setObjectName(u"gridLayout_32")
        self.groupBox_33 = QGroupBox(self.horizontalLayoutWidget_9)
        self.groupBox_33.setObjectName(u"groupBox_33")
        self.button_pgf_set_3 = QPushButton(self.groupBox_33)
        self.button_pgf_set_3.setObjectName(u"button_pgf_set_3")
        self.button_pgf_set_3.setGeometry(QRect(370, 100, 111, 41))
        self.label_61 = QLabel(self.groupBox_33)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(40, 220, 71, 16))
        self.pg_file_set_3 = QLineEdit(self.groupBox_33)
        self.pg_file_set_3.setObjectName(u"pg_file_set_3")
        self.pg_file_set_3.setGeometry(QRect(40, 100, 301, 41))
        self.protocol_file_set_3 = QLineEdit(self.groupBox_33)
        self.protocol_file_set_3.setObjectName(u"protocol_file_set_3")
        self.protocol_file_set_3.setGeometry(QRect(40, 180, 301, 41))
        self.label_60 = QLabel(self.groupBox_33)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(40, 300, 101, 16))
        self.button_protocol_set_3 = QPushButton(self.groupBox_33)
        self.button_protocol_set_3.setObjectName(u"button_protocol_set_3")
        self.button_protocol_set_3.setGeometry(QRect(370, 180, 111, 41))
        self.label_59 = QLabel(self.groupBox_33)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(40, 140, 61, 16))
        self.button_onl_analysis_set_3 = QPushButton(self.groupBox_33)
        self.button_onl_analysis_set_3.setObjectName(u"button_onl_analysis_set_3")
        self.button_onl_analysis_set_3.setGeometry(QRect(370, 260, 111, 41))
        self.online_analysis_file_set_3 = QLineEdit(self.groupBox_33)
        self.online_analysis_file_set_3.setObjectName(u"online_analysis_file_set_3")
        self.online_analysis_file_set_3.setGeometry(QRect(40, 260, 301, 41))

        self.gridLayout_32.addWidget(self.groupBox_33, 0, 0, 1, 1)


        self.horizontalLayout_14.addLayout(self.gridLayout_32)

        self.gridLayout_33 = QGridLayout()
        self.gridLayout_33.setObjectName(u"gridLayout_33")
        self.groupBox_34 = QGroupBox(self.horizontalLayoutWidget_9)
        self.groupBox_34.setObjectName(u"groupBox_34")
        self.A_com1 = QComboBox(self.groupBox_34)
        self.A_com1.setObjectName(u"A_com1")
        self.A_com1.setGeometry(QRect(30, 100, 141, 41))
        self.A_com2 = QComboBox(self.groupBox_34)
        self.A_com2.setObjectName(u"A_com2")
        self.A_com2.setGeometry(QRect(190, 100, 141, 41))
        self.A1 = QLineEdit(self.groupBox_34)
        self.A1.setObjectName(u"A1")
        self.A1.setGeometry(QRect(350, 100, 131, 41))
        self.A_com3 = QComboBox(self.groupBox_34)
        self.A_com3.setObjectName(u"A_com3")
        self.A_com3.setGeometry(QRect(30, 180, 141, 41))
        self.A2 = QLineEdit(self.groupBox_34)
        self.A2.setObjectName(u"A2")
        self.A2.setGeometry(QRect(190, 180, 291, 41))
        self.label_227 = QLabel(self.groupBox_34)
        self.label_227.setObjectName(u"label_227")
        self.label_227.setGeometry(QRect(30, 140, 81, 16))
        self.label_228 = QLabel(self.groupBox_34)
        self.label_228.setObjectName(u"label_228")
        self.label_228.setGeometry(QRect(190, 140, 91, 16))
        self.label_229 = QLabel(self.groupBox_34)
        self.label_229.setObjectName(u"label_229")
        self.label_229.setGeometry(QRect(350, 140, 81, 16))
        self.label_230 = QLabel(self.groupBox_34)
        self.label_230.setObjectName(u"label_230")
        self.label_230.setGeometry(QRect(30, 220, 71, 16))
        self.label_231 = QLabel(self.groupBox_34)
        self.label_231.setObjectName(u"label_231")
        self.label_231.setGeometry(QRect(190, 220, 141, 16))
        self.horizontalLayoutWidget_10 = QWidget(self.groupBox_34)
        self.horizontalLayoutWidget_10.setObjectName(u"horizontalLayoutWidget_10")
        self.horizontalLayoutWidget_10.setGeometry(QRect(110, 340, 311, 51))
        self.horizontalLayout_6 = QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.button_batch_7 = QPushButton(self.horizontalLayoutWidget_10)
        self.button_batch_7.setObjectName(u"button_batch_7")

        self.horizontalLayout_6.addWidget(self.button_batch_7)

        self.Batch1_4 = QLineEdit(self.groupBox_34)
        self.Batch1_4.setObjectName(u"Batch1_4")
        self.Batch1_4.setGeometry(QRect(30, 260, 451, 41))
        self.label_62 = QLabel(self.groupBox_34)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(30, 310, 111, 16))

        self.gridLayout_33.addWidget(self.groupBox_34, 0, 0, 1, 1)


        self.horizontalLayout_14.addLayout(self.gridLayout_33)

        self.horizontalLayoutWidget_8 = QWidget(self.page)
        self.horizontalLayoutWidget_8.setObjectName(u"horizontalLayoutWidget_8")
        self.horizontalLayoutWidget_8.setGeometry(QRect(40, 0, 1551, 391))
        self.horizontalLayout_13 = QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_13.setObjectName(u"horizontalLayout_13")
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_28 = QGridLayout()
        self.gridLayout_28.setObjectName(u"gridLayout_28")
        self.groupBox_22 = QGroupBox(self.horizontalLayoutWidget_8)
        self.groupBox_22.setObjectName(u"groupBox_22")
        self.So_com1 = QComboBox(self.groupBox_22)
        self.So_com1.setObjectName(u"So_com1")
        self.So_com1.setGeometry(QRect(100, 50, 281, 41))
        self.label_199 = QLabel(self.groupBox_22)
        self.label_199.setObjectName(u"label_199")
        self.label_199.setGeometry(QRect(110, 90, 71, 16))
        self.So_com2 = QComboBox(self.groupBox_22)
        self.So_com2.setObjectName(u"So_com2")
        self.So_com2.setGeometry(QRect(100, 120, 281, 41))
        self.label_200 = QLabel(self.groupBox_22)
        self.label_200.setObjectName(u"label_200")
        self.label_200.setGeometry(QRect(110, 160, 71, 16))
        self.S1 = QLineEdit(self.groupBox_22)
        self.S1.setObjectName(u"S1")
        self.S1.setGeometry(QRect(110, 190, 131, 41))
        self.S2 = QLineEdit(self.groupBox_22)
        self.S2.setObjectName(u"S2")
        self.S2.setGeometry(QRect(250, 190, 131, 41))
        self.label_201 = QLabel(self.groupBox_22)
        self.label_201.setObjectName(u"label_201")
        self.label_201.setGeometry(QRect(110, 230, 71, 16))
        self.label_202 = QLabel(self.groupBox_22)
        self.label_202.setObjectName(u"label_202")
        self.label_202.setGeometry(QRect(250, 230, 71, 16))
        self.S3 = QLineEdit(self.groupBox_22)
        self.S3.setObjectName(u"S3")
        self.S3.setGeometry(QRect(110, 260, 61, 41))
        self.S4 = QLineEdit(self.groupBox_22)
        self.S4.setObjectName(u"S4")
        self.S4.setGeometry(QRect(180, 260, 61, 41))
        self.S5 = QLineEdit(self.groupBox_22)
        self.S5.setObjectName(u"S5")
        self.S5.setGeometry(QRect(250, 260, 61, 41))
        self.S6 = QLineEdit(self.groupBox_22)
        self.S6.setObjectName(u"S6")
        self.S6.setGeometry(QRect(320, 260, 61, 41))
        self.label_203 = QLabel(self.groupBox_22)
        self.label_203.setObjectName(u"label_203")
        self.label_203.setGeometry(QRect(110, 300, 71, 16))
        self.label_204 = QLabel(self.groupBox_22)
        self.label_204.setObjectName(u"label_204")
        self.label_204.setGeometry(QRect(180, 300, 71, 16))
        self.label_205 = QLabel(self.groupBox_22)
        self.label_205.setObjectName(u"label_205")
        self.label_205.setGeometry(QRect(250, 300, 71, 16))
        self.label_206 = QLabel(self.groupBox_22)
        self.label_206.setObjectName(u"label_206")
        self.label_206.setGeometry(QRect(320, 300, 71, 16))

        self.gridLayout_28.addWidget(self.groupBox_22, 0, 0, 1, 1)


        self.horizontalLayout_13.addLayout(self.gridLayout_28)

        self.gridLayout_29 = QGridLayout()
        self.gridLayout_29.setObjectName(u"gridLayout_29")
        self.groupBox_30 = QGroupBox(self.horizontalLayoutWidget_8)
        self.groupBox_30.setObjectName(u"groupBox_30")
        self.Ce_com1 = QComboBox(self.groupBox_30)
        self.Ce_com1.setObjectName(u"Ce_com1")
        self.Ce_com1.setGeometry(QRect(110, 50, 281, 41))
        self.Ce_com2 = QComboBox(self.groupBox_30)
        self.Ce_com2.setObjectName(u"Ce_com2")
        self.Ce_com2.setGeometry(QRect(110, 120, 281, 41))
        self.Ce1 = QLineEdit(self.groupBox_30)
        self.Ce1.setObjectName(u"Ce1")
        self.Ce1.setGeometry(QRect(110, 190, 131, 41))
        self.label_207 = QLabel(self.groupBox_30)
        self.label_207.setObjectName(u"label_207")
        self.label_207.setGeometry(QRect(120, 90, 71, 16))
        self.label_208 = QLabel(self.groupBox_30)
        self.label_208.setObjectName(u"label_208")
        self.label_208.setGeometry(QRect(120, 160, 71, 16))
        self.label_209 = QLabel(self.groupBox_30)
        self.label_209.setObjectName(u"label_209")
        self.label_209.setGeometry(QRect(110, 230, 71, 16))

        self.gridLayout_29.addWidget(self.groupBox_30, 0, 0, 1, 1)


        self.horizontalLayout_13.addLayout(self.gridLayout_29)

        self.gridLayout_30 = QGridLayout()
        self.gridLayout_30.setObjectName(u"gridLayout_30")
        self.groupBox_31 = QGroupBox(self.horizontalLayoutWidget_8)
        self.groupBox_31.setObjectName(u"groupBox_31")
        self.C1 = QLineEdit(self.groupBox_31)
        self.C1.setObjectName(u"C1")
        self.C1.setGeometry(QRect(90, 50, 81, 41))
        self.C2 = QLineEdit(self.groupBox_31)
        self.C2.setObjectName(u"C2")
        self.C2.setGeometry(QRect(200, 50, 81, 41))
        self.Co_com1 = QComboBox(self.groupBox_31)
        self.Co_com1.setObjectName(u"Co_com1")
        self.Co_com1.setGeometry(QRect(300, 50, 91, 41))
        self.C3 = QLineEdit(self.groupBox_31)
        self.C3.setObjectName(u"C3")
        self.C3.setGeometry(QRect(90, 120, 81, 41))
        self.C4 = QLineEdit(self.groupBox_31)
        self.C4.setObjectName(u"C4")
        self.C4.setGeometry(QRect(200, 120, 81, 41))
        self.C5 = QLineEdit(self.groupBox_31)
        self.C5.setObjectName(u"C5")
        self.C5.setGeometry(QRect(90, 190, 81, 41))
        self.C6 = QLineEdit(self.groupBox_31)
        self.C6.setObjectName(u"C6")
        self.C6.setGeometry(QRect(200, 190, 81, 41))
        self.C8 = QLineEdit(self.groupBox_31)
        self.C8.setObjectName(u"C8")
        self.C8.setGeometry(QRect(90, 260, 131, 41))
        self.C9 = QLineEdit(self.groupBox_31)
        self.C9.setObjectName(u"C9")
        self.C9.setGeometry(QRect(270, 260, 131, 41))
        self.label_210 = QLabel(self.groupBox_31)
        self.label_210.setObjectName(u"label_210")
        self.label_210.setGeometry(QRect(90, 90, 81, 16))
        self.label_211 = QLabel(self.groupBox_31)
        self.label_211.setObjectName(u"label_211")
        self.label_211.setGeometry(QRect(200, 90, 71, 16))
        self.label_212 = QLabel(self.groupBox_31)
        self.label_212.setObjectName(u"label_212")
        self.label_212.setGeometry(QRect(310, 90, 71, 16))
        self.label_213 = QLabel(self.groupBox_31)
        self.label_213.setObjectName(u"label_213")
        self.label_213.setGeometry(QRect(90, 160, 71, 16))
        self.label_214 = QLabel(self.groupBox_31)
        self.label_214.setObjectName(u"label_214")
        self.label_214.setGeometry(QRect(200, 160, 71, 16))
        self.label_215 = QLabel(self.groupBox_31)
        self.label_215.setObjectName(u"label_215")
        self.label_215.setGeometry(QRect(90, 230, 71, 16))
        self.label_216 = QLabel(self.groupBox_31)
        self.label_216.setObjectName(u"label_216")
        self.label_216.setGeometry(QRect(200, 230, 71, 16))
        self.label_217 = QLabel(self.groupBox_31)
        self.label_217.setObjectName(u"label_217")
        self.label_217.setGeometry(QRect(90, 270, 71, 16))
        self.label_218 = QLabel(self.groupBox_31)
        self.label_218.setObjectName(u"label_218")
        self.label_218.setGeometry(QRect(270, 300, 111, 16))
        self.C6_2 = QLineEdit(self.groupBox_31)
        self.C6_2.setObjectName(u"C6_2")
        self.C6_2.setGeometry(QRect(310, 190, 81, 41))
        self.label_219 = QLabel(self.groupBox_31)
        self.label_219.setObjectName(u"label_219")
        self.label_219.setGeometry(QRect(310, 230, 71, 16))

        self.gridLayout_30.addWidget(self.groupBox_31, 0, 0, 1, 1)


        self.horizontalLayout_13.addLayout(self.gridLayout_30)

        self.meta_data_loading_1.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.groupBox_23 = QGroupBox(self.page_2)
        self.groupBox_23.setObjectName(u"groupBox_23")
        self.groupBox_23.setGeometry(QRect(70, 30, 601, 351))
        self.extracellular_sol_com_1 = QComboBox(self.groupBox_23)
        self.extracellular_sol_com_1.setObjectName(u"extracellular_sol_com_1")
        self.extracellular_sol_com_1.setGeometry(QRect(160, 50, 281, 41))
        self.label_243 = QLabel(self.groupBox_23)
        self.label_243.setObjectName(u"label_243")
        self.label_243.setGeometry(QRect(160, 90, 121, 16))
        self.Intracellular_sol_com_1 = QComboBox(self.groupBox_23)
        self.Intracellular_sol_com_1.setObjectName(u"Intracellular_sol_com_1")
        self.Intracellular_sol_com_1.setGeometry(QRect(160, 140, 281, 41))
        self.label_244 = QLabel(self.groupBox_23)
        self.label_244.setObjectName(u"label_244")
        self.label_244.setGeometry(QRect(160, 180, 131, 16))
        self.ent_date_prep = QLineEdit(self.groupBox_23)
        self.ent_date_prep.setObjectName(u"ent_date_prep")
        self.ent_date_prep.setGeometry(QRect(20, 240, 151, 41))
        self.S2_3 = QLineEdit(self.groupBox_23)
        self.S2_3.setObjectName(u"S2_3")
        self.S2_3.setGeometry(QRect(210, 240, 151, 41))
        self.label_245 = QLabel(self.groupBox_23)
        self.label_245.setObjectName(u"label_245")
        self.label_245.setGeometry(QRect(20, 280, 111, 16))
        self.ent_ph_set = QLabel(self.groupBox_23)
        self.ent_ph_set.setObjectName(u"ent_ph_set")
        self.ent_ph_set.setGeometry(QRect(210, 280, 131, 16))
        self.ent_ph_int_set = QLineEdit(self.groupBox_23)
        self.ent_ph_int_set.setObjectName(u"ent_ph_int_set")
        self.ent_ph_int_set.setGeometry(QRect(400, 240, 151, 41))
        self.label_247 = QLabel(self.groupBox_23)
        self.label_247.setObjectName(u"label_247")
        self.label_247.setGeometry(QRect(400, 280, 121, 16))
        self.groupBox_4 = QGroupBox(self.page_2)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(690, 30, 621, 351))
        self.pg_file_set = QLineEdit(self.groupBox_4)
        self.pg_file_set.setObjectName(u"pg_file_set")
        self.pg_file_set.setGeometry(QRect(90, 70, 331, 41))
        self.protocol_file_set = QLineEdit(self.groupBox_4)
        self.protocol_file_set.setObjectName(u"protocol_file_set")
        self.protocol_file_set.setGeometry(QRect(90, 160, 331, 41))
        self.online_analysis_file_set = QLineEdit(self.groupBox_4)
        self.online_analysis_file_set.setObjectName(u"online_analysis_file_set")
        self.online_analysis_file_set.setGeometry(QRect(90, 250, 331, 41))
        self.button_pgf_set = QPushButton(self.groupBox_4)
        self.button_pgf_set.setObjectName(u"button_pgf_set")
        self.button_pgf_set.setGeometry(QRect(460, 70, 111, 41))
        self.button_protocol_set = QPushButton(self.groupBox_4)
        self.button_protocol_set.setObjectName(u"button_protocol_set")
        self.button_protocol_set.setGeometry(QRect(460, 160, 111, 41))
        self.button_onl_analysis_set = QPushButton(self.groupBox_4)
        self.button_onl_analysis_set.setObjectName(u"button_onl_analysis_set")
        self.button_onl_analysis_set.setGeometry(QRect(460, 250, 111, 41))
        self.label_2 = QLabel(self.groupBox_4)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(90, 110, 61, 16))
        self.label_3 = QLabel(self.groupBox_4)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(90, 200, 71, 16))
        self.label_5 = QLabel(self.groupBox_4)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(90, 290, 101, 16))
        self.groupBox_6 = QGroupBox(self.page_2)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(70, 390, 601, 401))
        self.experiment_type_desc = QLineEdit(self.groupBox_6)
        self.experiment_type_desc.setObjectName(u"experiment_type_desc")
        self.experiment_type_desc.setGeometry(QRect(130, 90, 331, 41))
        self.label_6 = QLabel(self.groupBox_6)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(130, 130, 111, 16))
        self.cell_type_desc = QLineEdit(self.groupBox_6)
        self.cell_type_desc.setObjectName(u"cell_type_desc")
        self.cell_type_desc.setGeometry(QRect(130, 170, 331, 41))
        self.label_7 = QLabel(self.groupBox_6)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(130, 210, 111, 16))
        self.min_number_cells = QLineEdit(self.groupBox_6)
        self.min_number_cells.setObjectName(u"min_number_cells")
        self.min_number_cells.setGeometry(QRect(130, 250, 121, 41))
        self.label_8 = QLabel(self.groupBox_6)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(130, 290, 111, 16))
        self.patched_cells = QLineEdit(self.groupBox_6)
        self.patched_cells.setObjectName(u"patched_cells")
        self.patched_cells.setGeometry(QRect(290, 250, 111, 41))
        self.label_9 = QLabel(self.groupBox_6)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(290, 290, 111, 16))
        self.groupBox_17 = QGroupBox(self.page_2)
        self.groupBox_17.setObjectName(u"groupBox_17")
        self.groupBox_17.setGeometry(QRect(690, 390, 621, 401))
        self.Batch1 = QLineEdit(self.groupBox_17)
        self.Batch1.setObjectName(u"Batch1")
        self.Batch1.setGeometry(QRect(80, 140, 451, 41))
        self.button_batch_1 = QPushButton(self.groupBox_17)
        self.button_batch_1.setObjectName(u"button_batch_1")
        self.button_batch_1.setGeometry(QRect(140, 220, 341, 31))
        self.label_4 = QLabel(self.groupBox_17)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(80, 180, 111, 16))
        self.groupBox_7 = QGroupBox(self.page_2)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(1330, 30, 251, 761))
        self.Load_meta_data_experiment_12 = QPushButton(self.groupBox_7)
        self.Load_meta_data_experiment_12.setObjectName(u"Load_meta_data_experiment_12")
        self.Load_meta_data_experiment_12.setGeometry(QRect(40, 40, 171, 31))
        self.add_pixmap_for_green = QLabel(self.groupBox_7)
        self.add_pixmap_for_green.setObjectName(u"add_pixmap_for_green")
        self.add_pixmap_for_green.setGeometry(QRect(100, 730, 91, 16))
        self.database_save = QPushButton(self.groupBox_7)
        self.database_save.setObjectName(u"database_save")
        self.database_save.setGeometry(QRect(40, 90, 171, 31))
        self.database_save_2 = QPushButton(self.groupBox_7)
        self.database_save_2.setObjectName(u"database_save_2")
        self.database_save_2.setGeometry(QRect(40, 140, 171, 31))
        self.meta_data_loading_1.addWidget(self.page_2)
        self.label_17 = QLabel(self.experiment_initialization_3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(30, 20, 461, 31))
        font = QFont()
        font.setFamilies([u"Segoe UI"])
        font.setPointSize(13)
        self.label_17.setFont(font)
        self.Notebook_2.addTab(self.experiment_initialization_3, "")
        self.batch_communication_3 = QWidget()
        self.batch_communication_3.setObjectName(u"batch_communication_3")
        self.stackedWidget = QStackedWidget(self.batch_communication_3)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, -10, 1601, 941))
        self.communication_access = QWidget()
        self.communication_access.setObjectName(u"communication_access")
        self.groupBox_21 = QGroupBox(self.communication_access)
        self.groupBox_21.setObjectName(u"groupBox_21")
        self.groupBox_21.setGeometry(QRect(20, 80, 1531, 551))
        self.label_40 = QLabel(self.groupBox_21)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(90, 40, 181, 20))
        self.label_41 = QLabel(self.groupBox_21)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(600, 40, 171, 20))
        self.receive_command1 = QTextEdit(self.groupBox_21)
        self.receive_command1.setObjectName(u"receive_command1")
        self.receive_command1.setGeometry(QRect(600, 60, 311, 411))
        self.response_command_1 = QTextEdit(self.groupBox_21)
        self.response_command_1.setObjectName(u"response_command_1")
        self.response_command_1.setGeometry(QRect(1110, 60, 321, 411))
        self.label_42 = QLabel(self.groupBox_21)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(1110, 40, 231, 20))
        self.button_submit_command = QPushButton(self.groupBox_21)
        self.button_submit_command.setObjectName(u"button_submit_command")
        self.button_submit_command.setGeometry(QRect(90, 490, 151, 31))
        self.button_clear_window = QPushButton(self.groupBox_21)
        self.button_clear_window.setObjectName(u"button_clear_window")
        self.button_clear_window.setGeometry(QRect(260, 490, 151, 31))
        self.sub_command1 = QTextEdit(self.groupBox_21)
        self.sub_command1.setObjectName(u"sub_command1")
        self.sub_command1.setGeometry(QRect(90, 60, 321, 411))
        self.button_batch_2 = QPushButton(self.communication_access)
        self.button_batch_2.setObjectName(u"button_batch_2")
        self.button_batch_2.setGeometry(QRect(670, 650, 191, 41))
        self.label_24 = QLabel(self.communication_access)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(20, 20, 481, 61))
        font1 = QFont()
        font1.setFamilies([u"HoloLens MDL2 Assets"])
        font1.setPointSize(15)
        self.label_24.setFont(font1)
        self.line = QFrame(self.communication_access)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(-50, 10, 1641, 16))
        font2 = QFont()
        font2.setPointSize(1)
        self.line.setFont(font2)
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.stackedWidget.addWidget(self.communication_access)
        self.select_commands = QWidget()
        self.select_commands.setObjectName(u"select_commands")
        self.groupBox_19 = QGroupBox(self.select_commands)
        self.groupBox_19.setObjectName(u"groupBox_19")
        self.groupBox_19.setGeometry(QRect(0, 20, 1251, 911))
        self.listWidget = ListView(self.groupBox_19)
        self.listWidget.setObjectName(u"listWidget")
        self.listWidget.setGeometry(QRect(560, 60, 256, 801))
        self.label = QLabel(self.groupBox_19)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(560, 40, 191, 16))
        self.label_26 = QLabel(self.groupBox_19)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(830, 40, 191, 16))
        self.label_27 = QLabel(self.groupBox_19)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(10, 40, 191, 16))
        self.label_28 = QLabel(self.groupBox_19)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(280, 40, 191, 16))
        self.scrollArea = QScrollArea(self.groupBox_19)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(280, 60, 261, 371))
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 259, 369))
        self.SeriesWidget = ListView(self.scrollAreaWidgetContents)
        self.SeriesWidget.setObjectName(u"SeriesWidget")
        self.SeriesWidget.setGeometry(QRect(0, 0, 261, 371))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_32 = QLabel(self.groupBox_19)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(10, 440, 191, 16))
        self.scrollArea_2 = QScrollArea(self.groupBox_19)
        self.scrollArea_2.setObjectName(u"scrollArea_2")
        self.scrollArea_2.setGeometry(QRect(10, 460, 251, 441))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setObjectName(u"scrollAreaWidgetContents_2")
        self.scrollAreaWidgetContents_2.setGeometry(QRect(0, 0, 249, 439))
        self.protocol_widget = ListView(self.scrollAreaWidgetContents_2)
        self.protocol_widget.setObjectName(u"protocol_widget")
        self.protocol_widget.setGeometry(QRect(0, 0, 251, 441))
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.pushButton_10 = QPushButton(self.groupBox_19)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(560, 860, 256, 41))
        self.scrollArea_3 = QScrollArea(self.groupBox_19)
        self.scrollArea_3.setObjectName(u"scrollArea_3")
        self.scrollArea_3.setGeometry(QRect(10, 60, 251, 371))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollAreaWidgetContents_3 = QWidget()
        self.scrollAreaWidgetContents_3.setObjectName(u"scrollAreaWidgetContents_3")
        self.scrollAreaWidgetContents_3.setGeometry(QRect(0, 0, 249, 369))
        self.general_commands_labels = ListView(self.scrollAreaWidgetContents_3)
        self.general_commands_labels.setObjectName(u"general_commands_labels")
        self.general_commands_labels.setGeometry(QRect(0, 0, 256, 371))
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.layoutWidget = QWidget(self.groupBox_19)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(830, 60, 399, 347))
        self.pyqt_window = QGridLayout(self.layoutWidget)
        self.pyqt_window.setObjectName(u"pyqt_window")
        self.pyqt_window.setContentsMargins(0, 0, 0, 0)
        self.scrollArea_4 = QScrollArea(self.groupBox_19)
        self.scrollArea_4.setObjectName(u"scrollArea_4")
        self.scrollArea_4.setGeometry(QRect(280, 460, 261, 441))
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollAreaWidgetContents_4 = QWidget()
        self.scrollAreaWidgetContents_4.setObjectName(u"scrollAreaWidgetContents_4")
        self.scrollAreaWidgetContents_4.setGeometry(QRect(0, 0, 259, 439))
        self.SeriesWidget_2 = ListView(self.scrollAreaWidgetContents_4)
        self.SeriesWidget_2.setObjectName(u"SeriesWidget_2")
        self.SeriesWidget_2.setGeometry(QRect(0, 0, 261, 441))
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.label_29 = QLabel(self.groupBox_19)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(280, 440, 191, 16))
        self.cfast_qc_2 = QLineEdit(self.groupBox_19)
        self.cfast_qc_2.setObjectName(u"cfast_qc_2")
        self.cfast_qc_2.setGeometry(QRect(970, 520, 121, 31))
        self.rseries_qc = QLineEdit(self.groupBox_19)
        self.rseries_qc.setObjectName(u"rseries_qc")
        self.rseries_qc.setGeometry(QRect(830, 460, 121, 31))
        self.label_15 = QLabel(self.groupBox_19)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(830, 440, 91, 16))
        self.label_10 = QLabel(self.groupBox_19)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(970, 490, 47, 13))
        self.cfast_qc = QLineEdit(self.groupBox_19)
        self.cfast_qc.setObjectName(u"cfast_qc")
        self.cfast_qc.setGeometry(QRect(830, 520, 121, 31))
        self.label_14 = QLabel(self.groupBox_19)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(970, 550, 47, 13))
        self.label_12 = QLabel(self.groupBox_19)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(830, 490, 47, 13))
        self.cslow_qc = QLineEdit(self.groupBox_19)
        self.cslow_qc.setObjectName(u"cslow_qc")
        self.cslow_qc.setGeometry(QRect(970, 460, 121, 31))
        self.label_13 = QLabel(self.groupBox_19)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(830, 550, 47, 13))
        self.verticalLayoutWidget = QWidget(self.select_commands)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(1260, 30, 271, 151))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.pushButton_3 = QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName(u"pushButton_3")

        self.verticalLayout.addWidget(self.pushButton_3)

        self.pushButton_4 = QPushButton(self.verticalLayoutWidget)
        self.pushButton_4.setObjectName(u"pushButton_4")

        self.verticalLayout.addWidget(self.pushButton_4)

        self.pushButton_2 = QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName(u"pushButton_2")

        self.verticalLayout.addWidget(self.pushButton_2)

        self.label_16 = QLabel(self.select_commands)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(1260, 10, 151, 20))
        font3 = QFont()
        font3.setPointSize(10)
        self.label_16.setFont(font3)
        self.label_11 = QLabel(self.select_commands)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(1280, 100, 47, 13))
        self.stackedWidget.addWidget(self.select_commands)
        self.Notebook_2.addTab(self.batch_communication_3, "")
        self.camera_3 = QWidget()
        self.camera_3.setObjectName(u"camera_3")
        self.pushButton = QPushButton(self.camera_3)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(440, 40, 191, 31))
        self.groupBox = QGroupBox(self.camera_3)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(70, 90, 721, 591))
        self.Camera_Live_Feed = QGraphicsView(self.groupBox)
        self.Camera_Live_Feed.setObjectName(u"Camera_Live_Feed")
        self.Camera_Live_Feed.setGeometry(QRect(60, 50, 601, 471))
        self.button_start_camera = QPushButton(self.groupBox)
        self.button_start_camera.setObjectName(u"button_start_camera")
        self.button_start_camera.setGeometry(QRect(80, 540, 182, 21))
        self.button_stop_camera = QPushButton(self.groupBox)
        self.button_stop_camera.setObjectName(u"button_stop_camera")
        self.button_stop_camera.setGeometry(QRect(268, 540, 183, 23))
        self.button_take_snapshot = QPushButton(self.groupBox)
        self.button_take_snapshot.setObjectName(u"button_take_snapshot")
        self.button_take_snapshot.setGeometry(QRect(457, 540, 182, 23))
        self.groupBox_2 = QGroupBox(self.camera_3)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(810, 90, 721, 591))
        self.Taken_Snapshot = QGraphicsView(self.groupBox_2)
        self.Taken_Snapshot.setObjectName(u"Taken_Snapshot")
        self.Taken_Snapshot.setGeometry(QRect(60, 50, 601, 471))
        self.button_transfer_to_labbook = QPushButton(self.groupBox_2)
        self.button_transfer_to_labbook.setObjectName(u"button_transfer_to_labbook")
        self.button_transfer_to_labbook.setGeometry(QRect(460, 540, 182, 23))
        self.button_discard_snapshot = QPushButton(self.groupBox_2)
        self.button_discard_snapshot.setObjectName(u"button_discard_snapshot")
        self.button_discard_snapshot.setGeometry(QRect(83, 540, 182, 23))
        self.button_save_snapshot = QPushButton(self.groupBox_2)
        self.button_save_snapshot.setObjectName(u"button_save_snapshot")
        self.button_save_snapshot.setGeometry(QRect(271, 540, 183, 23))
        self.frame = QFrame(self.camera_3)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(70, 730, 1461, 211))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayoutWidget = QWidget(self.frame)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(0, 0, 1461, 211))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.label_31 = QLabel(self.camera_3)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(70, 710, 131, 16))
        self.label_18 = QLabel(self.camera_3)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(70, 30, 381, 51))
        font4 = QFont()
        font4.setPointSize(15)
        self.label_18.setFont(font4)
        self.Notebook_2.addTab(self.camera_3, "")

        self.gridLayout_2.addWidget(self.Notebook_2, 0, 1, 1, 1)


        self.retranslateUi(Config_Widget)

        self.Notebook_2.setCurrentIndex(1)
        self.meta_data_loading_1.setCurrentIndex(1)
        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Config_Widget)
    # setupUi

    def retranslateUi(self, Config_Widget):
        Config_Widget.setWindowTitle(QCoreApplication.translate("Config_Widget", u"Form", None))
        self.groupBox_32.setTitle(QCoreApplication.translate("Config_Widget", u"Staff", None))
        self.label_220.setText(QCoreApplication.translate("Config_Widget", u"Study director", None))
        self.label_221.setText(QCoreApplication.translate("Config_Widget", u"Technician", None))
        self.label_222.setText(QCoreApplication.translate("Config_Widget", u"Laboratory Code", None))
        self.groupBox_33.setTitle(QCoreApplication.translate("Config_Widget", u"Experiment Protocol", None))
        self.button_pgf_set_3.setText(QCoreApplication.translate("Config_Widget", u"Set", None))
        self.label_61.setText(QCoreApplication.translate("Config_Widget", u"Protocol File", None))
        self.label_60.setText(QCoreApplication.translate("Config_Widget", u"Online Analysis File", None))
        self.button_protocol_set_3.setText(QCoreApplication.translate("Config_Widget", u"Set", None))
        self.label_59.setText(QCoreApplication.translate("Config_Widget", u"PGF File", None))
        self.button_onl_analysis_set_3.setText(QCoreApplication.translate("Config_Widget", u"Set", None))
        self.groupBox_34.setTitle(QCoreApplication.translate("Config_Widget", u"Archiving", None))
        self.label_227.setText(QCoreApplication.translate("Config_Widget", u"Model Code", None))
        self.label_228.setText(QCoreApplication.translate("Config_Widget", u"Project Code", None))
        self.label_229.setText(QCoreApplication.translate("Config_Widget", u"Study Code", None))
        self.label_230.setText(QCoreApplication.translate("Config_Widget", u"Data path", None))
        self.label_231.setText(QCoreApplication.translate("Config_Widget", u"File name template", None))
        self.button_batch_7.setText(QCoreApplication.translate("Config_Widget", u"Setup Communication and open Communication Test Tool", None))
        self.label_62.setText(QCoreApplication.translate("Config_Widget", u"Control File Path", None))
        self.groupBox_22.setTitle(QCoreApplication.translate("Config_Widget", u"Solutions", None))
        self.label_199.setText(QCoreApplication.translate("Config_Widget", u"EC Type", None))
        self.label_200.setText(QCoreApplication.translate("Config_Widget", u"IC  Type", None))
        self.S1.setText("")
        self.label_201.setText(QCoreApplication.translate("Config_Widget", u"EC Lot #", None))
        self.label_202.setText(QCoreApplication.translate("Config_Widget", u"IC lot #", None))
        self.label_203.setText(QCoreApplication.translate("Config_Widget", u"T [\u00b0C]", None))
        self.label_204.setText(QCoreApplication.translate("Config_Widget", u"F [ml/min]", None))
        self.label_205.setText(QCoreApplication.translate("Config_Widget", u"I [nm]", None))
        self.label_206.setText(QCoreApplication.translate("Config_Widget", u"e", None))
        self.groupBox_30.setTitle(QCoreApplication.translate("Config_Widget", u"Cells", None))
        self.label_207.setText(QCoreApplication.translate("Config_Widget", u"License ID", None))
        self.label_208.setText(QCoreApplication.translate("Config_Widget", u"Cell line", None))
        self.label_209.setText(QCoreApplication.translate("Config_Widget", u"Passage #", None))
        self.groupBox_31.setTitle(QCoreApplication.translate("Config_Widget", u"Compound", None))
        self.label_210.setText(QCoreApplication.translate("Config_Widget", u"Sample Code", None))
        self.label_211.setText(QCoreApplication.translate("Config_Widget", u"Lot #", None))
        self.label_212.setText(QCoreApplication.translate("Config_Widget", u"Salt Code", None))
        self.label_213.setText(QCoreApplication.translate("Config_Widget", u"Sample Id", None))
        self.label_214.setText(QCoreApplication.translate("Config_Widget", u"MW [Da]", None))
        self.label_215.setText(QCoreApplication.translate("Config_Widget", u"Weight [mg]", None))
        self.label_216.setText(QCoreApplication.translate("Config_Widget", u"Solvent", None))
        self.label_217.setText(QCoreApplication.translate("Config_Widget", u"Stocks [mM]", None))
        self.label_218.setText(QCoreApplication.translate("Config_Widget", u"Concentration [\u00b5M]", None))
        self.label_219.setText(QCoreApplication.translate("Config_Widget", u"Volumn [\u00b5L]", None))
        self.groupBox_23.setTitle(QCoreApplication.translate("Config_Widget", u"Extracelullar and intracellular solutions", None))
        self.label_243.setText(QCoreApplication.translate("Config_Widget", u"Extracellular Solution", None))
        self.label_244.setText(QCoreApplication.translate("Config_Widget", u"Intracellular solution", None))
        self.ent_date_prep.setText("")
        self.label_245.setText(QCoreApplication.translate("Config_Widget", u"Date of Preparation ", None))
        self.ent_ph_set.setText(QCoreApplication.translate("Config_Widget", u"pH of External Solution", None))
        self.label_247.setText(QCoreApplication.translate("Config_Widget", u"Ph of internal solution", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("Config_Widget", u"Patchmaster Setup Files", None))
        self.button_pgf_set.setText(QCoreApplication.translate("Config_Widget", u"Set", None))
        self.button_protocol_set.setText(QCoreApplication.translate("Config_Widget", u"Set", None))
        self.button_onl_analysis_set.setText(QCoreApplication.translate("Config_Widget", u"Set", None))
        self.label_2.setText(QCoreApplication.translate("Config_Widget", u"PGF File", None))
        self.label_3.setText(QCoreApplication.translate("Config_Widget", u"Protocol File", None))
        self.label_5.setText(QCoreApplication.translate("Config_Widget", u"Online Analysis File", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("Config_Widget", u"Experiment Metadata", None))
        self.label_6.setText(QCoreApplication.translate("Config_Widget", u"Experiment Type", None))
        self.label_7.setText(QCoreApplication.translate("Config_Widget", u"Cell Type", None))
        self.label_8.setText(QCoreApplication.translate("Config_Widget", u"Min # of Cells", None))
        self.label_9.setText(QCoreApplication.translate("Config_Widget", u" # of Cells patched", None))
        self.groupBox_17.setTitle(QCoreApplication.translate("Config_Widget", u"Set Batch Communication Settings", None))
        self.button_batch_1.setText(QCoreApplication.translate("Config_Widget", u"Setup Communication and open Communication Test Tool", None))
        self.label_4.setText(QCoreApplication.translate("Config_Widget", u"Control File Path", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("Config_Widget", u"Button ToolBar", None))
        self.Load_meta_data_experiment_12.setText(QCoreApplication.translate("Config_Widget", u"Load Form", None))
        self.add_pixmap_for_green.setText(QCoreApplication.translate("Config_Widget", u"Connected...", None))
        self.database_save.setText(QCoreApplication.translate("Config_Widget", u"Save to Database", None))
        self.database_save_2.setText(QCoreApplication.translate("Config_Widget", u"Delete Form", None))
        self.label_17.setText(QCoreApplication.translate("Config_Widget", u"Setup Experiment and Connection to Patchmaster", None))
        self.Notebook_2.setTabText(self.Notebook_2.indexOf(self.experiment_initialization_3), QCoreApplication.translate("Config_Widget", u"Experiment Initialization", None))
        self.groupBox_21.setTitle(QCoreApplication.translate("Config_Widget", u"Test the Connection to the Patchmaster", None))
        self.label_40.setText(QCoreApplication.translate("Config_Widget", u"Submit your Commands", None))
        self.label_41.setText(QCoreApplication.translate("Config_Widget", u"Control File received", None))
        self.label_42.setText(QCoreApplication.translate("Config_Widget", u"Batch Communication Response", None))
        self.button_submit_command.setText(QCoreApplication.translate("Config_Widget", u"Submit Command", None))
        self.button_clear_window.setText(QCoreApplication.translate("Config_Widget", u"Stop Submitting", None))
        self.button_batch_2.setText(QCoreApplication.translate("Config_Widget", u"Setup Experiment", None))
        self.label_24.setText(QCoreApplication.translate("Config_Widget", u"Test Patchmaster Batch Communication", None))
        self.groupBox_19.setTitle(QCoreApplication.translate("Config_Widget", u"Protocol Editor", None))
        self.label.setText(QCoreApplication.translate("Config_Widget", u"Final Patch Clamping Sequence:", None))
        self.label_26.setText(QCoreApplication.translate("Config_Widget", u"Notebook Online Analysis:", None))
        self.label_27.setText(QCoreApplication.translate("Config_Widget", u"Dragable Labels", None))
        self.label_28.setText(QCoreApplication.translate("Config_Widget", u"Dragable Executable Series", None))
        self.label_32.setText(QCoreApplication.translate("Config_Widget", u"Dragable Protocols", None))
        self.pushButton_10.setText(QCoreApplication.translate("Config_Widget", u"Clear Sequences", None))
        self.label_29.setText(QCoreApplication.translate("Config_Widget", u"Dragable QC-Checks", None))
        self.label_15.setText(QCoreApplication.translate("Config_Widget", u"Quality Metrics", None))
        self.label_10.setText(QCoreApplication.translate("Config_Widget", u"Cslow", None))
        self.label_14.setText(QCoreApplication.translate("Config_Widget", u"Cell", None))
        self.label_12.setText(QCoreApplication.translate("Config_Widget", u"Rseries", None))
        self.label_13.setText(QCoreApplication.translate("Config_Widget", u"Cfast", None))
        self.pushButton_3.setText(QCoreApplication.translate("Config_Widget", u"Start Experiment", None))
        self.pushButton_4.setText(QCoreApplication.translate("Config_Widget", u"Stop Experiment", None))
        self.pushButton_2.setText(QCoreApplication.translate("Config_Widget", u"Save Plot", None))
        self.label_16.setText(QCoreApplication.translate("Config_Widget", u"Execution of Experiment:", None))
        self.label_11.setText("")
        self.Notebook_2.setTabText(self.Notebook_2.indexOf(self.batch_communication_3), QCoreApplication.translate("Config_Widget", u"Batch Communication", None))
        self.pushButton.setText(QCoreApplication.translate("Config_Widget", u"Initalize Camera", None))
        self.groupBox.setTitle(QCoreApplication.translate("Config_Widget", u"Live Camera Feed", None))
        self.button_start_camera.setText(QCoreApplication.translate("Config_Widget", u"Start Camera", None))
        self.button_stop_camera.setText(QCoreApplication.translate("Config_Widget", u"Stop Camera", None))
        self.button_take_snapshot.setText(QCoreApplication.translate("Config_Widget", u"Take Snapshot", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Config_Widget", u"Snapshot Overview", None))
        self.button_transfer_to_labbook.setText(QCoreApplication.translate("Config_Widget", u"Transfer to Labbook", None))
        self.button_discard_snapshot.setText(QCoreApplication.translate("Config_Widget", u"Discard Snapshot", None))
        self.button_save_snapshot.setText(QCoreApplication.translate("Config_Widget", u"Save Snapshot", None))
        self.label_31.setText(QCoreApplication.translate("Config_Widget", u"Image Galery:", None))
        self.label_18.setText(QCoreApplication.translate("Config_Widget", u"Camera Module for Image Integration", None))
        self.Notebook_2.setTabText(self.Notebook_2.indexOf(self.camera_3), QCoreApplication.translate("Config_Widget", u"Camera", None))
    # retranslateUi

        









