# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'settings_window.ui'
##
## Created by: Qt User Interface Compiler version 6.1.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *  # type: ignore
from PySide6.QtGui import *  # type: ignore
from PySide6.QtWidgets import *  # type: ignore


class Ui_Settings(object):
    def setupUi(self, Settings):
        if not Settings.objectName():
            Settings.setObjectName(u"Settings")
        Settings.resize(999, 716)
        self.frame = QFrame(Settings)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(0, 10, 201, 671))
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet(u"QFrame{\n"
"	background-color: \"#232629\";\n"
"\n"
"}")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label_15 = QLabel(self.frame)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(0, 0, 239, 40))
        font = QFont()
        font.setPointSize(25)
        self.label_15.setFont(font)
        self.Set_default_user = QPushButton(self.frame)
        self.Set_default_user.setObjectName(u"Set_default_user")
        self.Set_default_user.setGeometry(QRect(10, 70, 181, 23))
        self.initialize_devices = QPushButton(self.frame)
        self.initialize_devices.setObjectName(u"initialize_devices")
        self.initialize_devices.setGeometry(QRect(10, 150, 181, 23))
        self.plot_appearance = QPushButton(self.frame)
        self.plot_appearance.setObjectName(u"plot_appearance")
        self.plot_appearance.setGeometry(QRect(10, 230, 181, 23))
        self.save_location = QPushButton(self.frame)
        self.save_location.setObjectName(u"save_location")
        self.save_location.setGeometry(QRect(10, 310, 181, 23))
        self.connect_to_webserver = QPushButton(self.frame)
        self.connect_to_webserver.setObjectName(u"connect_to_webserver")
        self.connect_to_webserver.setGeometry(QRect(10, 390, 181, 23))
        self.stackedWidget_4 = QStackedWidget(Settings)
        self.stackedWidget_4.setObjectName(u"stackedWidget_4")
        self.stackedWidget_4.setGeometry(QRect(220, 10, 741, 591))
        self.stackedWidget_4.setStyleSheet(u"QWidget{\n"
"	background-color: \"#232629\";\n"
"\n"
"}")
        self.page_7 = QWidget()
        self.page_7.setObjectName(u"page_7")
        self.label_11 = QLabel(self.page_7)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 10, 261, 31))
        self.label_11.setFont(font)
        self.label_16 = QLabel(self.page_7)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 131, 62, 17))
        self.label_17 = QLabel(self.page_7)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 79, 56, 20))
        self.lineEdit_4 = QLineEdit(self.page_7)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(78, 79, 371, 20))
        self.checkBox_7 = QCheckBox(self.page_7)
        self.checkBox_7.setObjectName(u"checkBox_7")
        self.checkBox_7.setGeometry(QRect(78, 131, 371, 17))
        self.checkBox_8 = QCheckBox(self.page_7)
        self.checkBox_8.setObjectName(u"checkBox_8")
        self.checkBox_8.setGeometry(QRect(78, 180, 371, 17))
        self.label_18 = QLabel(self.page_7)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 180, 49, 17))
        self.stackedWidget_4.addWidget(self.page_7)
        self.page_8 = QWidget()
        self.page_8.setObjectName(u"page_8")
        self.label_12 = QLabel(self.page_8)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 10, 181, 21))
        font1 = QFont()
        font1.setPointSize(15)
        self.label_12.setFont(font1)
        self.label_13 = QLabel(self.page_8)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 80, 151, 16))
        self.label_14 = QLabel(self.page_8)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 150, 151, 16))
        self.label_19 = QLabel(self.page_8)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 220, 151, 16))
        self.comboBox = QComboBox(self.page_8)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(180, 70, 251, 31))
        self.comboBox_2 = QComboBox(self.page_8)
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(180, 140, 251, 31))
        self.comboBox_3 = QComboBox(self.page_8)
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setGeometry(QRect(180, 210, 251, 31))
        self.pushButton_14 = QPushButton(self.page_8)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(460, 140, 131, 23))
        self.pushButton_15 = QPushButton(self.page_8)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(460, 210, 131, 23))
        self.pushButton_13 = QPushButton(self.page_8)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(460, 70, 131, 21))
        self.stackedWidget_4.addWidget(self.page_8)
        self.Set_plot_appearance = QWidget()
        self.Set_plot_appearance.setObjectName(u"Set_plot_appearance")
        self.stackedWidget_4.addWidget(self.Set_plot_appearance)
        self.set_file_locations = QWidget()
        self.set_file_locations.setObjectName(u"set_file_locations")
        self.stackedWidget_4.addWidget(self.set_file_locations)
        self.connect_to_database = QWidget()
        self.connect_to_database.setObjectName(u"connect_to_database")
        self.label_20 = QLabel(self.connect_to_database)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 10, 191, 16))
        self.label_20.setFont(font1)
        self.label_21 = QLabel(self.connect_to_database)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 80, 91, 16))
        self.label_22 = QLabel(self.connect_to_database)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 140, 111, 16))
        self.label_23 = QLabel(self.connect_to_database)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(10, 210, 101, 16))
        self.lineEdit_3 = QLineEdit(self.connect_to_database)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(130, 70, 251, 31))
        self.lineEdit_5 = QLineEdit(self.connect_to_database)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(130, 130, 251, 31))
        self.lineEdit_6 = QLineEdit(self.connect_to_database)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(300, 250, 251, 31))
        self.pushButton_16 = QPushButton(self.connect_to_database)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(410, 140, 131, 23))
        self.pushButton_17 = QPushButton(self.connect_to_database)
        self.pushButton_17.setObjectName(u"pushButton_17")
        self.pushButton_17.setGeometry(QRect(410, 80, 131, 23))
        self.label_24 = QLabel(self.connect_to_database)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(180, 260, 101, 16))
        self.label_25 = QLabel(self.connect_to_database)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(180, 320, 101, 16))
        self.lineEdit_7 = QLineEdit(self.connect_to_database)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(300, 310, 251, 31))
        self.stackedWidget_4.addWidget(self.connect_to_database)
        self.frame_2 = QFrame(Settings)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(220, 610, 741, 71))
        self.frame_2.setStyleSheet(u"QFrame{\n"
"	background-color: \"#232629\";\n"
"\n"
"}")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.save_settings = QPushButton(self.frame_2)
        self.save_settings.setObjectName(u"save_settings")
        self.save_settings.setGeometry(QRect(440, 20, 131, 31))
        self.quit_settings = QPushButton(self.frame_2)
        self.quit_settings.setObjectName(u"quit_settings")
        self.quit_settings.setGeometry(QRect(590, 20, 131, 31))

        self.retranslateUi(Settings)

        self.stackedWidget_4.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(Settings)
    # setupUi

    def retranslateUi(self, Settings):
        Settings.setWindowTitle(QCoreApplication.translate("Settings", u"Form", None))
        self.label_15.setText(QCoreApplication.translate("Settings", u"Settings", None))
        self.Set_default_user.setText(QCoreApplication.translate("Settings", u"Set Default User", None))
        self.initialize_devices.setText(QCoreApplication.translate("Settings", u"Initialize Devices", None))
        self.plot_appearance.setText(QCoreApplication.translate("Settings", u"Set Plot Appearance", None))
        self.save_location.setText(QCoreApplication.translate("Settings", u"Set File Locations", None))
        self.connect_to_webserver.setText(QCoreApplication.translate("Settings", u"Connect to Database", None))
        self.label_11.setText(QCoreApplication.translate("Settings", u"Set Default User", None))
        self.label_16.setText(QCoreApplication.translate("Settings", u"Admin Mode:", None))
        self.label_17.setText(QCoreApplication.translate("Settings", u"User Name:", None))
        self.checkBox_7.setText(QCoreApplication.translate("Settings", u"CheckBox", None))
        self.checkBox_8.setText(QCoreApplication.translate("Settings", u"CheckBox", None))
        self.label_18.setText(QCoreApplication.translate("Settings", u"Pro Mode:", None))
        self.label_12.setText(QCoreApplication.translate("Settings", u"Initialize Devices", None))
        self.label_13.setText(QCoreApplication.translate("Settings", u"Select Camera Interface:", None))
        self.label_14.setText(QCoreApplication.translate("Settings", u"Select pH Meter:", None))
        self.label_19.setText(QCoreApplication.translate("Settings", u"Select ...", None))
        self.pushButton_14.setText(QCoreApplication.translate("Settings", u"Initialize pH meter", None))
        self.pushButton_15.setText(QCoreApplication.translate("Settings", u"Initalize ...", None))
        self.pushButton_13.setText(QCoreApplication.translate("Settings", u"Initalize Camera", None))
        self.label_20.setText(QCoreApplication.translate("Settings", u"Connect to database", None))
        self.label_21.setText(QCoreApplication.translate("Settings", u"Connect via IP:", None))
        self.label_22.setText(QCoreApplication.translate("Settings", u"Open DataBase File:", None))
        self.label_23.setText(QCoreApplication.translate("Settings", u"Advanced Settings:", None))
        self.pushButton_16.setText(QCoreApplication.translate("Settings", u"Open Filepath", None))
        self.pushButton_17.setText(QCoreApplication.translate("Settings", u"Connect with IP", None))
        self.label_24.setText(QCoreApplication.translate("Settings", u"Username:", None))
        self.label_25.setText(QCoreApplication.translate("Settings", u"Password:", None))
        self.save_settings.setText(QCoreApplication.translate("Settings", u"Save Settings", None))
        self.quit_settings.setText(QCoreApplication.translate("Settings", u"Quit Setting", None))
    # retranslateUi

