[tool.poetry]
name = "biophysicalessentials"
version = "0.13.0"
description = "Data Analysis Platform for Electrophysiological Recordings"
authors = ["David Zimmermann, Maximilian Zeidler"]

[tool.poetry.dependencies]
python = "^3.11,<3.13"
PySide6 = "6.10.2"
PySide6_Addons = "6.10.2"
PySide6_Essentials = "6.10.2"
duckdb = "1.5.0"
qbstyles = "0.1.4"
numpy = "1.26.4"
natsort = "8.4.0"
pandas = "3.0.1"
matplotlib = "3.10.8"
pillow = "12.1.1"
pyqtgraph = "0.14.0"
pytest = "9.0.2"
qt-material = "2.17"
scikit-learn = "1.8.0"
scipy = "1.17.1"
seaborn = "0.13.2"
statsmodels = "0.14.6"
statannotations = "0.7.2"
pyabf = "2.3.8"
mplcursors = "0.7"
contourpy = "1.3.3"
threadpoolctl = "3.6.0"
tzdata = "2025.3"
picologging = "0.9.3"
SQLAlchemy = "2.0.48"
pyinstaller = "6.19.0"
pytest-qt = "4.5.0"
pypylon = "26.2.1"
debugpy = "1.8.20"

[build-system] 
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


