name: Build and Release

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: |
        pip install poetry

    - name: Configure Poetry
      working-directory: src
      run: |
        poetry config virtualenvs.create false

    - name: Install dependencies
      working-directory: src  
      run: |
        poetry install

    - name: Build with PyInstaller
      working-directory: src
      run: |
        pyinstaller start.spec

    - name: Fix macOS Gatekeeper issue
      if: runner.os == 'macOS'
      working-directory: src
      run: |
        xattr -cr dist   
        
          
    - name: Upload dist directory
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ matrix.os }}
        path: src/dist
    